#pragma once
#include "Entities/Platformer/PlatformerEntity.h"

#include "Entities/Platformer/Squally/Squally.h"

// NPCS
#include "Entities/Platformer/Npcs/Knight.h"

// Enemies
#include "Entities/Platformer/Enemies/Castle/BossWitch.h"
#include "Entities/Platformer/Enemies/Castle/Executioner.h"
#include "Entities/Platformer/Enemies/Castle/Ghost.h"
#include "Entities/Platformer/Enemies/Castle/Guard.h"
#include "Entities/Platformer/Enemies/Castle/Harpy.h"
#include "Entities/Platformer/Enemies/Castle/Jack.h"
#include "Entities/Platformer/Enemies/Castle/Reaper.h"
#include "Entities/Platformer/Enemies/Castle/SkeletonMage.h"
#include "Entities/Platformer/Enemies/Castle/VampireLord.h"
#include "Entities/Platformer/Enemies/Castle/Vampiress.h"
#include "Entities/Platformer/Enemies/Castle/Zombie.h"

#include "Entities/Platformer/Enemies/Caverns/BlackWidow.h"
#include "Entities/Platformer/Enemies/Caverns/BossKrampus.h"
#include "Entities/Platformer/Enemies/Caverns/EarthElemental.h"
#include "Entities/Platformer/Enemies/Caverns/EarthGolem.h"
#include "Entities/Platformer/Enemies/Caverns/ForestGolem.h"
#include "Entities/Platformer/Enemies/Caverns/Genie.h"
#include "Entities/Platformer/Enemies/Caverns/RockGolem.h"
#include "Entities/Platformer/Enemies/Caverns/Shaman.h"
#include "Entities/Platformer/Enemies/Caverns/SkeletonArcher.h"
#include "Entities/Platformer/Enemies/Caverns/SkeletonNecromancer.h"
#include "Entities/Platformer/Enemies/Caverns/SkeletonWarrior.h"

#include "Entities/Platformer/Enemies/Forest/BossDragonOrcKing.h"
#include "Entities/Platformer/Enemies/Forest/Cyclops.h"
#include "Entities/Platformer/Enemies/Forest/Ent.h"
#include "Entities/Platformer/Enemies/Forest/EntMage.h"
#include "Entities/Platformer/Enemies/Forest/GoblinGruntBoar.h"
#include "Entities/Platformer/Enemies/Forest/GoblinGuard.h"
#include "Entities/Platformer/Enemies/Forest/GoblinShaman.h"
#include "Entities/Platformer/Enemies/Forest/GoblinWarriorPig.h"
#include "Entities/Platformer/Enemies/Forest/OrcGrunt.h"
#include "Entities/Platformer/Enemies/Forest/OrcWarrior.h"
#include "Entities/Platformer/Enemies/Forest/Troll.h"

#include "Entities/Platformer/Enemies/Jungle/BossRhinoman.h"
#include "Entities/Platformer/Enemies/Jungle/GoblinGrunt.h"
#include "Entities/Platformer/Enemies/Jungle/GoblinSwordsman.h"
#include "Entities/Platformer/Enemies/Jungle/GoblinWarrior.h"
#include "Entities/Platformer/Enemies/Jungle/JungleDragon.h"
#include "Entities/Platformer/Enemies/Jungle/Mantis.h"
#include "Entities/Platformer/Enemies/Jungle/Minotaur.h"
#include "Entities/Platformer/Enemies/Jungle/PigDemon.h"
#include "Entities/Platformer/Enemies/Jungle/PurpleDinosaur.h"
#include "Entities/Platformer/Enemies/Jungle/TikiGolem.h"
#include "Entities/Platformer/Enemies/Jungle/TikiWarrior.h"

#include "Entities/Platformer/Enemies/Mech/Robot.h"
#include "Entities/Platformer/Enemies/Mech/BossEvilEye.h"
#include "Entities/Platformer/Enemies/Mech/Exterminator.h"
#include "Entities/Platformer/Enemies/Mech/MechBoxDrone.h"
#include "Entities/Platformer/Enemies/Mech/MechDog.h"
#include "Entities/Platformer/Enemies/Mech/MechGolem.h"
#include "Entities/Platformer/Enemies/Mech/MechGolemDark.h"
#include "Entities/Platformer/Enemies/Mech/MechGuard.h"
#include "Entities/Platformer/Enemies/Mech/MiteBot.h"
#include "Entities/Platformer/Enemies/Mech/VikingBot.h"
#include "Entities/Platformer/Enemies/Mech/VikingBotSmall.h"

#include "Entities/Platformer/Enemies/Obelisk/Abomination.h"
#include "Entities/Platformer/Enemies/Obelisk/BatDemon.h"
#include "Entities/Platformer/Enemies/Obelisk/BossSkeletonKing.h"
#include "Entities/Platformer/Enemies/Obelisk/DarkDragon.h"
#include "Entities/Platformer/Enemies/Obelisk/DemonArcher.h"
#include "Entities/Platformer/Enemies/Obelisk/SkeletonBaron.h"
#include "Entities/Platformer/Enemies/Obelisk/SkeletonCleaver.h"
#include "Entities/Platformer/Enemies/Obelisk/SkeletonKnight.h"
#include "Entities/Platformer/Enemies/Obelisk/SkeletonPriestess.h"
#include "Entities/Platformer/Enemies/Obelisk/SkeletonPriestess.h"
#include "Entities/Platformer/Enemies/Obelisk/Undead.h"
#include "Entities/Platformer/Enemies/Obelisk/VoidDemon.h"

#include "Entities/Platformer/Enemies/Ruins/AnubisTiny.h"
#include "Entities/Platformer/Enemies/Ruins/AnubisWarrior.h"
#include "Entities/Platformer/Enemies/Ruins/BossEgyptianGoddess.h"
#include "Entities/Platformer/Enemies/Ruins/Lioness.h"
#include "Entities/Platformer/Enemies/Ruins/LionMan.h"
#include "Entities/Platformer/Enemies/Ruins/Medusa.h"
#include "Entities/Platformer/Enemies/Ruins/MedusaSmall.h"
#include "Entities/Platformer/Enemies/Ruins/Mermaid.h"
#include "Entities/Platformer/Enemies/Ruins/MummyPharaoh.h"
#include "Entities/Platformer/Enemies/Ruins/TigerMan.h"
#include "Entities/Platformer/Enemies/Ruins/Tigress.h"

#include "Entities/Platformer/Enemies/Snow/BossIceGolem.h"
#include "Entities/Platformer/Enemies/Snow/BossSanta.h"
#include "Entities/Platformer/Enemies/Snow/EvilSnowman.h"
#include "Entities/Platformer/Enemies/Snow/FrostDragon.h"
#include "Entities/Platformer/Enemies/Snow/FrostShooter.h"
#include "Entities/Platformer/Enemies/Snow/GoblinElf.h"
#include "Entities/Platformer/Enemies/Snow/IceGolem.h"
#include "Entities/Platformer/Enemies/Snow/TinyIceGolem.h"
#include "Entities/Platformer/Enemies/Snow/ToySoldierGoblin.h"
#include "Entities/Platformer/Enemies/Snow/WaterElemental.h"
#include "Entities/Platformer/Enemies/Snow/Yeti.h"
#include "Entities/Platformer/Enemies/Snow/YetiWarrior.h"

#include "Entities/Platformer/Enemies/Volcano/BossDemonKing.h"
#include "Entities/Platformer/Enemies/Volcano/CritterDemon.h"
#include "Entities/Platformer/Enemies/Volcano/DemonDragon.h"
#include "Entities/Platformer/Enemies/Volcano/DemonGhost.h"
#include "Entities/Platformer/Enemies/Volcano/DemonGrunt.h"
#include "Entities/Platformer/Enemies/Volcano/DemonRogue.h"
#include "Entities/Platformer/Enemies/Volcano/DemonShaman.h"
#include "Entities/Platformer/Enemies/Volcano/DemonSwordsman.h"
#include "Entities/Platformer/Enemies/Volcano/DemonWarrior.h"
#include "Entities/Platformer/Enemies/Volcano/FireElemental.h"
#include "Entities/Platformer/Enemies/Volcano/LavaGolem.h"
