#pragma once

#include "Scenes/Hexus/Opponents/Bosses/HexusOpponentDemonKing.h"
#include "Scenes/Hexus/Opponents/Bosses/HexusOpponentEgyptianGoddess.h"
#include "Scenes/Hexus/Opponents/Bosses/HexusOpponentEvilEye.h"
#include "Scenes/Hexus/Opponents/Bosses/HexusOpponentIceGolem.h"
#include "Scenes/Hexus/Opponents/Castle/HexusOpponentJack.h"
#include "Scenes/Hexus/Opponents/Bosses/HexusOpponentKrampus.h"
#include "Scenes/Hexus/Opponents/Bosses/HexusOpponentOrcKing.h"
#include "Scenes/Hexus/Opponents/Bosses/HexusOpponentRhinoman.h"
#include "Scenes/Hexus/Opponents/Bosses/HexusOpponentSanta.h"
#include "Scenes/Hexus/Opponents/Bosses/HexusOpponentSkeletonKing.h"
#include "Scenes/Hexus/Opponents/Castle/HexusOpponentCentaur.h"
#include "Scenes/Hexus/Opponents/Castle/HexusOpponentWitch.h"
#include "Scenes/Hexus/Opponents/Kickstarter/HexusOpponentKnight.h"
#include "Scenes/Hexus/Opponents/Npcs/HexusOpponentEgyptianMummy.h"