#pragma once

// Jungle
#include "Scenes/Hexus/Opponents/Jungle/HexusOpponentJungleBarbarian.h"
#include "Scenes/Hexus/Opponents/Jungle/HexusOpponentJungleDwarf.h"
#include "Scenes/Hexus/Opponents/Jungle/HexusOpponentJungleFighter.h"
#include "Scenes/Hexus/Opponents/Jungle/HexusOpponentJungleGeezer.h"
#include "Scenes/Hexus/Opponents/Jungle/HexusOpponentJungleGoblinGrunt.h"
#include "Scenes/Hexus/Opponents/Jungle/HexusOpponentJungleGoblinSwordsman.h"
#include "Scenes/Hexus/Opponents/Jungle/HexusOpponentJungleGoblinWarrior.h"
#include "Scenes/Hexus/Opponents/Jungle/HexusOpponentJungleHades.h"
#include "Scenes/Hexus/Opponents/Jungle/HexusOpponentJungleJungleDragon.h"
#include "Scenes/Hexus/Opponents/Jungle/HexusOpponentJungleMantis.h"
#include "Scenes/Hexus/Opponents/Jungle/HexusOpponentJungleMinotaur.h"
#include "Scenes/Hexus/Opponents/Jungle/HexusOpponentJunglePeasant.h"
#include "Scenes/Hexus/Opponents/Jungle/HexusOpponentJunglePigDemon.h"
#include "Scenes/Hexus/Opponents/Jungle/HexusOpponentJunglePirate.h"
#include "Scenes/Hexus/Opponents/Jungle/HexusOpponentJunglePrincess.h"
#include "Scenes/Hexus/Opponents/Jungle/HexusOpponentJunglePurpleDinosaur.h"
#include "Scenes/Hexus/Opponents/Jungle/HexusOpponentJungleRhinoman.h"
#include "Scenes/Hexus/Opponents/Jungle/HexusOpponentJungleThor.h"
#include "Scenes/Hexus/Opponents/Jungle/HexusOpponentJungleTikiGolem.h"
#include "Scenes/Hexus/Opponents/Jungle/HexusOpponentJungleTikiWarrior.h"
#include "Scenes/Hexus/Opponents/Jungle/HexusOpponentJungleViking.h"

// Tutorial
#include "Scenes/Hexus/Opponents/Tutorial/HexusOpponentTutorialA.h"
#include "Scenes/Hexus/Opponents/Tutorial/HexusOpponentTutorialB.h"
#include "Scenes/Hexus/Opponents/Tutorial/HexusOpponentTutorialC.h"
#include "Scenes/Hexus/Opponents/Tutorial/HexusOpponentTutorialD.h"
#include "Scenes/Hexus/Opponents/Tutorial/HexusOpponentTutorialE.h"
#include "Scenes/Hexus/Opponents/Tutorial/HexusOpponentTutorialF.h"

#include "Scenes/Hexus/Opponents/Bosses/HexusOpponentDemonKing.h"
#include "Scenes/Hexus/Opponents/Bosses/HexusOpponentEgyptianGoddess.h"
#include "Scenes/Hexus/Opponents/Bosses/HexusOpponentEvilEye.h"
#include "Scenes/Hexus/Opponents/Bosses/HexusOpponentIceGolem.h"
#include "Scenes/Hexus/Opponents/Castle/HexusOpponentJack.h"
#include "Scenes/Hexus/Opponents/Bosses/HexusOpponentKrampus.h"
#include "Scenes/Hexus/Opponents/Bosses/HexusOpponentOrcKing.h"
#include "Scenes/Hexus/Opponents/Bosses/HexusOpponentRhinoman.h"
#include "Scenes/Hexus/Opponents/Bosses/HexusOpponentSanta.h"
#include "Scenes/Hexus/Opponents/Bosses/HexusOpponentSkeletonKing.h"
#include "Scenes/Hexus/Opponents/Castle/HexusOpponentCentaur.h"
#include "Scenes/Hexus/Opponents/Castle/HexusOpponentWitch.h"

#include "Scenes/Hexus/Opponents/Kickstarter/HexusOpponentKnight.h"
#include "Scenes/Hexus/Opponents/Npcs/HexusOpponentEgyptianMummy.h"