#pragma once

#include "Scenes/Hexus/Opponents/Bosses/HexusOpponentDataDemonKing.h"
#include "Scenes/Hexus/Opponents/Bosses/HexusOpponentDataEgyptianGoddess.h"
#include "Scenes/Hexus/Opponents/Bosses/HexusOpponentDataEvilEye.h"
#include "Scenes/Hexus/Opponents/Bosses/HexusOpponentDataIceGolem.h"
#include "Scenes/Hexus/Opponents/Bosses/HexusOpponentDataJack.h"
#include "Scenes/Hexus/Opponents/Bosses/HexusOpponentDataKrampus.h"
#include "Scenes/Hexus/Opponents/Bosses/HexusOpponentDataOrcKing.h"
#include "Scenes/Hexus/Opponents/Bosses/HexusOpponentDataRhinoman.h"
#include "Scenes/Hexus/Opponents/Bosses/HexusOpponentDataSanta.h"
#include "Scenes/Hexus/Opponents/Bosses/HexusOpponentDataSkeletonKing.h"
#include "Scenes/Hexus/Opponents/Bosses/HexusOpponentDataWitch.h"
#include "Scenes/Hexus/Opponents/Kickstarter/HexusOpponentDataKnight.h"
#include "Scenes/Hexus/Opponents/Npcs/HexusOpponentDataEgyptianMummy.h"