////////////////////////////////////////////////////////////////////////////////////////////
// THIS C++ FILE IS GENERATED DO NOT EDIT. RUN GenerateResources.py TO GENERATE THIS FILE //
////////////////////////////////////////////////////////////////////////////////////////////
#pragma once
#include <string>

namespace ParticleResources
{
	extern const std::string BeamMeUp;
	extern const std::string BlueNether;
	extern const std::string BluePlasma;
	extern const std::string BlueStarCircle;
	extern const std::string BlueSwirl;
	extern const std::string BlueSwirlLarge;
	extern const std::string ColorfulStars;
	extern const std::string Confetti;
	extern const std::string Dust;
	extern const std::string Electric;
	extern const std::string Fireflies;
	extern const std::string Fireflies2;
	extern const std::string Galaxy;
	extern const std::string Gust;
	extern const std::string HackableGlow;
	extern const std::string Heal;
	extern const std::string Hexus_Aura;
	extern const std::string Hexus_BlueAura;
	extern const std::string Hexus_BlueAuraLarge;
	extern const std::string Hexus_CardEffects_Bite;
	extern const std::string Hexus_CardEffects_DustPoof;
	extern const std::string Hexus_CardEffects_DustStorm;
	extern const std::string Hexus_CardEffects_FireBlast;
	extern const std::string Hexus_CardEffects_Flow;
	extern const std::string Hexus_CardEffects_FocusRing;
	extern const std::string Hexus_CardEffects_FrostCircle;
	extern const std::string Hexus_CardEffects_Gush;
	extern const std::string Hexus_CardEffects_Lightning;
	extern const std::string Hexus_CardEffects_MagicBurst;
	extern const std::string Hexus_CardEffects_MeteorAlt;
	extern const std::string Hexus_CardEffects_MeteorBlue;
	extern const std::string Hexus_CardEffects_MeteorPurple;
	extern const std::string Hexus_CardEffects_Nether;
	extern const std::string Hexus_CardEffects_Poison;
	extern const std::string Hexus_CardEffects_RadialAura;
	extern const std::string Hexus_CardEffects_RadialFire;
	extern const std::string Hexus_CardEffects_RadialGalaxy;
	extern const std::string Hexus_CardEffects_RadialStorm;
	extern const std::string Hexus_CardEffects_SelectionPulse;
	extern const std::string Hexus_CardEffects_SpinningMagic;
	extern const std::string Hexus_CardEffects_Splash;
	extern const std::string Hexus_CardEffects_StarBurst;
	extern const std::string Hexus_CardEffects_StarHit;
	extern const std::string Hexus_CardEffects_TargetPulse;
	extern const std::string Hexus_PurpleAura;
	extern const std::string Hexus_PurpleAuraLarge;
	extern const std::string Hexus_RowEffects_FlameWall;
	extern const std::string Hexus_RowEffects_Rain;
	extern const std::string Hexus_WhiteAura;
	extern const std::string Hover;
	extern const std::string ItemGlow;
	extern const std::string MindBlast;
	extern const std::string Objects_MagicWall;
	extern const std::string Objects_Smoke;
	extern const std::string Objects_VaseBreak;
	extern const std::string Platformer_Combat_Abilities_Speed;
	extern const std::string Platformer_Combat_LevelUp;
	extern const std::string Platformer_Hacking_HackerRain1;
	extern const std::string Platformer_Hacking_HackerRain2;
	extern const std::string Platformer_Hacking_HackerRain3;
	extern const std::string Platformer_Hacking_HackerRain4;
	extern const std::string Platformer_Hacking_HackerRain5;
	extern const std::string Platformer_Hacking_HackerRainOrange1;
	extern const std::string Platformer_Hacking_HackerRainOrange2;
	extern const std::string Platformer_Hacking_HackerRainOrange3;
	extern const std::string Platformer_Hacking_HackerRainOrange4;
	extern const std::string Platformer_Hacking_HackerRainOrange5;
	extern const std::string Poison;
	extern const std::string Portals_DarkPortal;
	extern const std::string Portals_PortalEdge;
	extern const std::string Portals_PortalEdgeDark;
	extern const std::string Portals_PortalEye;
	extern const std::string Portals_PortalFire;
	extern const std::string Portals_PortalFrost;
	extern const std::string Portals_PortalNature;
	extern const std::string Portals_PortalNatureEdge;
	extern const std::string Portals_PortalSand;
	extern const std::string Portals_PortalVoid;
	extern const std::string Portals_PortalWater;
	extern const std::string Portals_PortalWind;
	extern const std::string Rain;
	extern const std::string Rain2;
	extern const std::string Spark;
	extern const std::string Sparkles;
	extern const std::string Sparks;
	extern const std::string Static;
	extern const std::string WarpGate;
	extern const std::string WarpPoint;
	extern const std::string Wind;
};
