///////////////////////////////////////////////////////////////////////////////////////////////
// THIS C++ FILE IS GENERATED DO NOT EDIT. MAKE CHANGES IN THE RESOURCE TEXT TEMPLATING FILE //
///////////////////////////////////////////////////////////////////////////////////////////////

#pragma once
#include <string>

using namespace std;

class Resources
{
public:
	static const string CloseNormal;
	static const string CloseSelected;
	static const string HelloWorld;
	static const string Background_DesertBG;
	static const string Background_GrassBG;
	static const string Background_SnowBG;
	static const string Debug_VertexNode;
	static const string Editor_CrossHair;
	static const string Editor_DunkleosteusEditor;
	static const string Editor_HorizontalSelector;
	static const string Editor_LevelEditPanel;
	static const string Editor_PterodactylEditor;
	static const string Editor_RaptorEditor;
	static const string Fonts_arial;
	static const string Fonts_Marker_Felt;
	static const string GUI_Egg;
	static const string GUI_Heart0;
	static const string GUI_Heart1;
	static const string GUI_Heart10;
	static const string GUI_Heart2;
	static const string GUI_Heart3;
	static const string GUI_Heart4;
	static const string GUI_Heart5;
	static const string GUI_Heart6;
	static const string GUI_Heart7;
	static const string GUI_Heart8;
	static const string GUI_Heart9;
	static const string GUI_MindPowerBack;
	static const string GUI_MindPowerCover;
	static const string Levels_Debug;
	static const string Menus_SolidBlackSquare;
	static const string Menus_CreditsMenu_CreditsBG;
	static const string Menus_CreditsMenu_UFO;
	static const string Menus_IngameMenu_IngameMenu;
	static const string Menus_IntroMenu_SpeechBubble;
	static const string Menus_IntroMenu_Scene1_Scene1BG;
	static const string Menus_IntroMenu_Scene1_Scene1_NPC;
	static const string Menus_IntroMenu_Scene1_Scene1_Player;
	static const string Menus_IntroMenu_Scene2_Scene2BG;
	static const string Menus_IntroMenu_Scene3_Scene3BG;
	static const string Menus_IntroMenu_Scene3_Scene3FG;
	static const string Menus_IntroMenu_Scene3_Scene3_Apple;
	static const string Menus_IntroMenu_Scene3_Scene3_Player;
	static const string Menus_IntroMenu_Scene3_Scene3_TRex;
	static const string Menus_OptionsMenu_OptionsMenu;
	static const string Menus_TitleScreen_HorizontalSelect;
	static const string Menus_TitleScreen_TitleScreen;
	static const string Menus_TitleScreen_VerticalSelect;
	static const string Menus_WorldMap_Apple;
	static const string Menus_WorldMap_AppleGrayed;
	static const string Menus_WorldMap_Banana;
	static const string Menus_WorldMap_BananaGrayed;
	static const string Menus_WorldMap_DashedLineLocked;
	static const string Menus_WorldMap_DashedLineUnlocked;
	static const string Menus_WorldMap_LevelNodeLocked;
	static const string Menus_WorldMap_LevelNodeUnlocked;
	static const string Menus_WorldMap_Orange;
	static const string Menus_WorldMap_OrangeGrayed;
	static const string Menus_WorldMap_ProgressPanel;
	static const string Menus_WorldMap_WorldMap;
	static const string Menus_WorldMap_WorldMapSelector;
	static const string Objects_Bridge;
	static const string Objects_CloudLarge;
	static const string Objects_CloudSmall;
	static const string Objects_Lava;
	static const string Objects_OceanMine;
	static const string Objects_OceanMineLarge;
	static const string Objects_PillarLargeRuins;
	static const string Objects_PillarSmallRuins;
	static const string Objects_PlatformBridge;
	static const string Objects_PlatformRuins;
	static const string Objects_SignGlideLeft;
	static const string Objects_SignGlideRight;
	static const string Objects_SignSkullLeft;
	static const string Objects_SignSkullRight;
	static const string Objects_SpikeBall;
	static const string Objects_SpikesB;
	static const string Objects_SpikesSmallB;
	static const string Objects_SpikesSmallT;
	static const string Objects_SpikesT;
	static const string Objects_Water;
	static const string Objects_WaterTop;
	static const string Objects_CheckPoint_OuthouseClosed;
	static const string Objects_CheckPoint_OutHouseOpen;
	static const string Objects_Collectables_Apple;
	static const string Objects_Collectables_Banana;
	static const string Objects_Collectables_Egg;
	static const string Objects_Collectables_Orange;
	static const string Objects_Exit_Exit;
	static const string Particles_BreathParticle;
	static const string Particles_DeathParticle;
	static const string Particles_MindPowerParticle;
	static const string Particles_ProjectileParticle;
	static const string Particles_RainParticle;
	static const string Particles_SandParticle;
	static const string Particles_SnowflakeParticle;
	static const string Particles_WindParticle;
	static const string Sprites_EggProjectile;
	static const string Sprites_Collectables_Egg;
	static const string Sprites_Dunkleosteus_Dunkleosteus;
	static const string Sprites_Player_Idle;
	static const string Sprites_Player_Player_Attack;
	static const string Sprites_Player_Player_Attack2;
	static const string Sprites_Player_Player_Glide;
	static const string Sprites_Player_Player_Underwater;
	static const string Sprites_Pterodactyl_Pterodactyl;
	static const string Sprites_Pterodactyl_PterodactylIdle;
	static const string Sprites_Raptor_Attack;
	static const string Sprites_Raptor_Idle;
	static const string Sprites_Raptor_Jump;
	static const string Sprites_Raptor_Run;
	static const string Tiles_Bridge;
	static const string Tiles_Grass;
	static const string Tiles_Lava;
	static const string Tiles_Ruins;
	static const string Tiles_Sand;
	static const string Tiles_Snow;
	static const string Tiles_TileMap;
	static const string Tiles_Water;
};
