#pragma once

#include "Scenes/Hexus/Opponents/Mech/HexusOpponentAtreus.h"
#include "Scenes/Hexus/Opponents/Mech/HexusOpponentEvilEye.h"
#include "Scenes/Hexus/Opponents/Mech/HexusOpponentExterminator.h"
#include "Scenes/Hexus/Opponents/Mech/HexusOpponentIllia.h"
#include "Scenes/Hexus/Opponents/Mech/HexusOpponentLeon.h"
#include "Scenes/Hexus/Opponents/Mech/HexusOpponentMara.h"
#include "Scenes/Hexus/Opponents/Mech/HexusOpponentMarcel.h"
#include "Scenes/Hexus/Opponents/Mech/HexusOpponentMechGolemDark.h"
#include "Scenes/Hexus/Opponents/Mech/HexusOpponentPiper.h"
#include "Scenes/Hexus/Opponents/Mech/HexusOpponentQueenElise.h"
#include "Scenes/Hexus/Opponents/Mech/HexusOpponentRadon.h"
#include "Scenes/Hexus/Opponents/Mech/HexusOpponentRoboGolem.h"
#include "Scenes/Hexus/Opponents/Mech/HexusOpponentXenon.h"
#include "Scenes/Hexus/Opponents/Mech/HexusOpponentYsara.h"
